In [1]:
# 'HistoricoFormularioReferencia.aspx?codigoCVM={code}&tipo=itr&ano=0' 
import pandas as pd
import numpy as np

In [6]:
empresas_df = pd.read_csv('url_demonstrativos.csv')
receitas_1_df = pd.read_excel('Receitas_1.xlsx')
receitas_2_df = pd.read_excel('Receitas_2.xlsx')
receitas_3_df = pd.read_excel('Receitas_3.xlsx')
lucros_1_df = pd.read_excel('Lucros_1.xlsx')
lucros_2_df = pd.read_excel('Lucros_2.xlsx')
lucros_3_df = pd.read_excel('Lucros_3.xlsx')

In [5]:
receitas_1_df.head()

,Conta,Descrição,01/01/2020 a 31/03/2020,01/01/2019 a 31/03/2019
0,3.01,Receita de Venda de Bens e/ou Serviços,8.2,7.777
1,3.01,Receita de Venda de Bens e/ou Serviços,NaN,NaN
2,3.01,Receita de Venda de Bens e/ou Serviços,NaN,NaN
3,3.01,Receita de Venda de Bens e/ou Serviços,288.924,152.031
4,3.01,Receita de Venda de Bens e/ou Serviços,494.396,486.806

In [9]:
empresas_df = empresas_df.rename(columns={'Unnamed: 0':'Empresas'})

In [10]:
empresas_df.head()

,Empresas,0,1,2
0,3R PETROLEUM ÓLEO E GÁS S.A,http://www.rad.cvm.gov.br/ENETCONSULTA/frmGere...,http://www.rad.cvm.gov.br/ENETCONSULTA/frmGere...,http://www.rad.cvm.gov.br/ENETCONSULTA/frmGere...
1,524 PARTICIPACOES S.A.,http://www.rad.cvm.gov.br/ENETCONSULTA/frmGere...,http://www.rad.cvm.gov.br/ENETCONSULTA/frmGere...,http://www.rad.cvm.gov.br/ENETCONSULTA/frmGere...
2,ADVANCED DIGITAL HEALTH MEDICINA PREVENTIVA S.A.,http://www.rad.cvm.gov.br/ENETCONSULTA/frmGere...,http://www.rad.cvm.gov.br/ENETCONSULTA/frmGere...,http://www.rad.cvm.gov.br/ENETCONSULTA/frmGere...
3,AERIS IND. E COM. DE EQUIP. GERACAO DE ENERGIA...,http://www.rad.cvm.gov.br/ENETCONSULTA/frmGere...,http://www.rad.cvm.gov.br/ENETCONSULTA/frmGere...,http://www.rad.cvm.gov.br/ENETCONSULTA/frmGere...
4,AES TIETE ENERGIA SA,http://www.rad.cvm.gov.br/ENETCONSULTA/frmGere...,http://www.rad.cvm.gov.br/ENETCONSULTA/frmGere...,http://www.rad.cvm.gov.br/ENETCONSULTA/frmGere...

In [13]:
receitas_2_df.head(2)

,Conta,Descrição,01/04/2020 a 30/06/2020,01/01/2020 a 30/06/2020,01/04/2019 a 30/06/2019,01/01/2019 a 30/06/2019
0,3.01,Receita de Venda de Bens e/ou Serviços,9.052,17.252,7.73,15.507
1,3.01,Receita de Venda de Bens e/ou Serviços,NaN,NaN,NaN,NaN

In [14]:
lucros_2_df.head(2)

,Conta,Descrição,01/04/2020 a 30/06/2020,01/01/2020 a 30/06/2020,01/04/2019 a 30/06/2019,01/01/2019 a 30/06/2019
0,3.11,Lucro/Prejuízo Consolidado do Período,-42.319,-70.271,-37.821,-46.841
1,3.11,Lucro/Prejuízo do Período,-32,-97,-29,-104

In [15]:
columns_to_drop = ['01/01/2020 a 30/06/2020','01/01/2019 a 30/06/2019']
receitas_2_df.drop(columns=columns_to_drop, inplace=True)
lucros_2_df.drop(columns=columns_to_drop, inplace=True)

In [16]:
receitas_3_df.head(2)

,Conta,Descrição,01/07/2020 a 30/09/2020,01/01/2020 a 30/09/2020,01/07/2019 a 30/09/2019,01/01/2019 a 30/09/2019
0,3.01,Receita de Venda de Bens e/ou Serviços,10.304,27.556,8.049,23.556
1,3.01,Receita de Venda de Bens e/ou Serviços,NaN,NaN,NaN,NaN

In [17]:
columns_to_drop = ['01/01/2020 a 30/09/2020','01/01/2019 a 30/09/2019']
receitas_3_df.drop(columns=columns_to_drop, inplace=True)
lucros_3_df.drop(columns=columns_to_drop, inplace=True)

In [24]:
receitas_df = pd.concat([empresas_df['Empresas'],receitas_1_df, receitas_2_df[['01/04/2020 a 30/06/2020','01/04/2019 a 30/06/2019']], receitas_3_df[['01/07/2020 a 30/09/2020','01/07/2019 a 30/09/2019']]], axis=1).set_index('Empresas')

In [25]:
receitas_df.head(2)

,Conta,Descrição,01/01/2020 a 31/03/2020,01/01/2019 a 31/03/2019,01/04/2020 a 30/06/2020,01/04/2019 a 30/06/2019,01/07/2020 a 30/09/2020,01/07/2019 a 30/09/2019
Empresas,,,,,,,,
3R PETROLEUM ÓLEO E GÁS S.A,3.01,Receita de Venda de Bens e/ou Serviços,8.2,7.777,9.052,7.73,10.304,8.049
524 PARTICIPACOES S.A.,3.01,Receita de Venda de Bens e/ou Serviços,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
lucros_df = pd.concat([empresas_df['Empresas'],lucros_1_df, lucros_2_df[['01/04/2020 a 30/06/2020','01/04/2019 a 30/06/2019']], lucros_3_df[['01/07/2020 a 30/09/2020','01/07/2019 a 30/09/2019']]], axis=1).set_index('Empresas')

In [27]:
lucros_df.head()

,Conta,Descrição,01/01/2020 a 31/03/2020,01/01/2019 a 31/03/2019,01/04/2020 a 30/06/2020,01/04/2019 a 30/06/2019,01/07/2020 a 30/09/2020,01/07/2019 a 30/09/2019
Empresas,,,,,,,,
3R PETROLEUM ÓLEO E GÁS S.A,3.11,Lucro/Prejuízo Consolidado do Período,-27.952,-9.02,-42.319,-37.821,-12.749,-24.486
524 PARTICIPACOES S.A.,3.11,Lucro/Prejuízo do Período,-65,-75,-32,-29,-15,-18
ADVANCED DIGITAL HEALTH MEDICINA PREVENTIVA S.A.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AERIS IND. E COM. DE EQUIP. GERACAO DE ENERGIA S/A,3.11,Lucro/Prejuízo Consolidado do Período,16.605,10.482,24.521,9.888,56.445,28.046
AES TIETE ENERGIA SA,3.11,Lucro/Prejuízo Consolidado do Período,75.319,62.014,118.959,35.438,51.143,97.109

In [28]:
receitas_df.isnull().sum()

Conta                       9
Descrição                   9
01/01/2020 a 31/03/2020    35
01/01/2019 a 31/03/2019    35
01/04/2020 a 30/06/2020    34
01/04/2019 a 30/06/2019    37
01/07/2020 a 30/09/2020    29
01/07/2019 a 30/09/2019    33
dtype: int64

In [29]:
lucros_df.isnull().sum()

Conta                      17
Descrição                  17
01/01/2020 a 31/03/2020    41
01/01/2019 a 31/03/2019    41
01/04/2020 a 30/06/2020    42
01/04/2019 a 30/06/2019    42
01/07/2020 a 30/09/2020    29
01/07/2019 a 30/09/2019    29
dtype: int64

In [30]:
lucros_df['Descrição'].unique()

array(['Lucro/Prejuízo Consolidado do Período',
       'Lucro/Prejuízo do Período', nan,
       'Reversão dos Juros sobre Capital Próprio',
       'Resultado Líquido das Operações Continuadas'], dtype=object)

In [31]:
receitas_df.columns

Index(['Conta', 'Descrição', '01/01/2020 a 31/03/2020',
       '01/01/2019 a 31/03/2019', '01/04/2020 a 30/06/2020',
       '01/04/2019 a 30/06/2019', '01/07/2020 a 30/09/2020',
       '01/07/2019 a 30/09/2019'],
      dtype='object')

In [32]:
columns_to_reindex = ['Conta', 'Descrição','01/01/2019 a 31/03/2019','01/04/2019 a 30/06/2019','01/07/2019 a 30/09/2019',\
                      '01/01/2020 a 31/03/2020','01/04/2020 a 30/06/2020','01/07/2020 a 30/09/2020']

In [33]:
receitas_df = receitas_df.reindex(columns=columns_to_reindex)
receitas_df.head()

,Conta,Descrição,01/01/2019 a 31/03/2019,01/04/2019 a 30/06/2019,01/07/2019 a 30/09/2019,01/01/2020 a 31/03/2020,01/04/2020 a 30/06/2020,01/07/2020 a 30/09/2020
Empresas,,,,,,,,
3R PETROLEUM ÓLEO E GÁS S.A,3.01,Receita de Venda de Bens e/ou Serviços,7.777,7.73,8.049,8.2,9.052,10.304
524 PARTICIPACOES S.A.,3.01,Receita de Venda de Bens e/ou Serviços,NaN,NaN,NaN,NaN,NaN,NaN
ADVANCED DIGITAL HEALTH MEDICINA PREVENTIVA S.A.,3.01,Receita de Venda de Bens e/ou Serviços,NaN,NaN,NaN,NaN,NaN,NaN
AERIS IND. E COM. DE EQUIP. GERACAO DE ENERGIA S/A,3.01,Receita de Venda de Bens e/ou Serviços,152.031,179.669,220.669,288.924,464.031,705.823
AES TIETE ENERGIA SA,3.01,Receita de Venda de Bens e/ou Serviços,486.806,485.057,510.924,494.396,475.207,509.374

In [34]:
lucros_df = lucros_df.reindex(columns=columns_to_reindex)
lucros_df.head()

,Conta,Descrição,01/01/2019 a 31/03/2019,01/04/2019 a 30/06/2019,01/07/2019 a 30/09/2019,01/01/2020 a 31/03/2020,01/04/2020 a 30/06/2020,01/07/2020 a 30/09/2020
Empresas,,,,,,,,
3R PETROLEUM ÓLEO E GÁS S.A,3.11,Lucro/Prejuízo Consolidado do Período,-9.02,-37.821,-24.486,-27.952,-42.319,-12.749
524 PARTICIPACOES S.A.,3.11,Lucro/Prejuízo do Período,-75,-29,-18,-65,-32,-15
ADVANCED DIGITAL HEALTH MEDICINA PREVENTIVA S.A.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AERIS IND. E COM. DE EQUIP. GERACAO DE ENERGIA S/A,3.11,Lucro/Prejuízo Consolidado do Período,10.482,9.888,28.046,16.605,24.521,56.445
AES TIETE ENERGIA SA,3.11,Lucro/Prejuízo Consolidado do Período,62.014,35.438,97.109,75.319,118.959,51.143

In [35]:
lucros_df.tail()

,Conta,Descrição,01/01/2019 a 31/03/2019,01/04/2019 a 30/06/2019,01/07/2019 a 30/09/2019,01/01/2020 a 31/03/2020,01/04/2020 a 30/06/2020,01/07/2020 a 30/09/2020
Empresas,,,,,,,,
WEG S.A.,3.11,Lucro/Prejuízo Consolidado do Período,308.207,395.260,424.540,453.975,526.517,653.612
WETZEL S.A.,3.11,Lucro/Prejuízo Consolidado do Período,-7.144,-12.388,-9.693,-6.934,-5.191,-4.204
WHIRLPOOL S.A.,3.11,Lucro/Prejuízo Consolidado do Período,348.550,187.704,1.087.057,104.603,59.168,279.217
WLM PART. E COMÉRCIO DE MÁQUINAS E VEÍCULOS S.A.,3.11,Lucro/Prejuízo Consolidado do Período,6.628,8.455,14.041,9.481,9.866,18.728
YDUQS PARTICIPACOES S.A.,3.11,Lucro/Prejuízo Consolidado do Período,240.797,194.773,152.511,167.888,-79.542,112.476

In [36]:
receitas_df.to_excel('Receitas_limpo.xlsx')
lucros_df.to_excel('Lucros_limpo.xlsx')

In [37]:
testando = pd.read_excel('Receitas_limpo.xlsx')
testando.head()

,Empresas,Conta,Descrição,01/01/2019 a 31/03/2019,01/04/2019 a 30/06/2019,01/07/2019 a 30/09/2019,01/01/2020 a 31/03/2020,01/04/2020 a 30/06/2020,01/07/2020 a 30/09/2020
0,3R PETROLEUM ÓLEO E GÁS S.A,3.01,Receita de Venda de Bens e/ou Serviços,7.777,7.73,8.049,8.2,9.052,10.304
1,524 PARTICIPACOES S.A.,3.01,Receita de Venda de Bens e/ou Serviços,NaN,NaN,NaN,NaN,NaN,NaN
2,ADVANCED DIGITAL HEALTH MEDICINA PREVENTIVA S.A.,3.01,Receita de Venda de Bens e/ou Serviços,NaN,NaN,NaN,NaN,NaN,NaN
3,AERIS IND. E COM. DE EQUIP. GERACAO DE ENERGIA...,3.01,Receita de Venda de Bens e/ou Serviços,152.031,179.669,220.669,288.924,464.031,705.823
4,AES TIETE ENERGIA SA,3.01,Receita de Venda de Bens e/ou Serviços,486.806,485.057,510.924,494.396,475.207,509.374